-- MySQL Script generated by MySQL Workbench
-- Wed Feb 10 11:57:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ORCA_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ORCA_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ORCA_DB` DEFAULT CHARACTER SET utf8 ;
USE `ORCA_DB` ;

-- -----------------------------------------------------
-- Table `ORCA_DB`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ORCA_DB`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_ID` INT NULL,
  `course_ID` VARCHAR(45) NULL,
  `Timestamp` DATETIME NULL,
  `event_type` VARCHAR(45) NULL,
  `activity_name` VARCHAR(45) NULL,
  `activity_details` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `student_ID`
    FOREIGN KEY (`student_ID`)
    REFERENCES `ORCA_DB`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ORCA_DB`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ORCA_DB`.`student` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
